### ISSUE TITLE
[v1.0.0] Kleine Tippfehler Titelseite & S.74

### ISSUE THREAD

**Issue by birawaich** [renezurbruegg/pvk_nus1#1]
Guten Abend René

Beim Überfliegen sind mir folgende beiden Fehler aufgefallen:

- Titelseite
(3.) Gleichung (Durchflutung): J ist klein. (Es ist im Buch gross. Aber würde diese Formel auch mit einem Zeitabhängigen J(t) funktionieren?)
- S. 74 (5.2  Charakteristische Gleichungen von Kapazität und Induktivität)
Bei Spule, Strom: "u[L] von Tau" Tau ist nicht in Klammern, könnte verwirren
Bei Kondensator, Strom: C ist klein geschrieben, könnte verwirren, ist ja nicht abhängig von Zeit

Ich hoffe, das Gefundene sind auch Fehler.
Ansonsten danke für das tolle Skript!

**Comment by renezurbruegg** [comment]
Danke vielmals für die Rückmeldung!

Habe das Skript angepasst. 

Zur 3. Gleichung: 
Die Formel funktioniert auch mit einer zeitabhängigen Stromdichte. 
Falls man die Stromdichte etwas allgemeiner definiert und auch eine zeitliche Änderung des D-Feldes als Strom (Verschiebungsstrom) definiert, so erhält man die [4. Maxwellgleichung in Integralform](https://de.wikipedia.org/wiki/Maxwell-Gleichungen#Übersicht)

Das zeitabhängige Grössen klein geschrieben werden ist übrigens reine Definitionssache und wird nicht zwingend überall so durchgesetzt. 
In NuS wird diese Konvention glaube ich auch nur für u, i und j definiert.
Die magnetische Flussdichte wird Beispielsweise als B(t) angegeben. 

Einfach als Hinweis - deine Korrekturen sind berechtigt und sinnvoll ! :)

Gruss
René

**Comment by birawaich** [comment]
Danke für die rasche Antwort!
